CREATE PROCEDURE REMOVE_DUPLICATE_ITEM_NAMES()
    LANGUAGE JAVA PARAMETER STYLE JAVA
    MODIFIES SQL DATA
    EXTERNAL NAME 'emcshop.db.MigrationSprocs.removeDuplicateItemNames';

CALL REMOVE_DUPLICATE_ITEM_NAMES();
DROP PROCEDURE REMOVE_DUPLICATE_ITEM_NAMES;
