CREATE PROCEDURE FIX_1_15_ITEM_NAMES()
LANGUAGE JAVA PARAMETER STYLE JAVA
MODIFIES SQL DATA
EXTERNAL NAME 'emcshop.db.MigrationSprocs.updateItemsWhoseOldNamesAreUsedByExistingItemsIn1_15';

CALL FIX_1_15_ITEM_NAMES();

CALL UPDATE_ITEM_NAMES();
CALL POPULATE_ITEMS_TABLE();
