CALL UPDATE_ITEM_NAMES();

CREATE TABLE bonuses_fees(
	since TIMESTAMP,
	horse INT NOT NULL DEFAULT 0,
	lock INT NOT NULL DEFAULT 0,
	eggify INT NOT NULL DEFAULT 0,
	vault INT NOT NULL DEFAULT 0,
	sign_in INT NOT NULL DEFAULT 0,
	vote INT NOT NULL DEFAULT 0
);
INSERT INTO bonuses_fees (since) VALUES (NULL);