CREATE PROCEDURE MIGRATE()
LANGUAGE JAVA PARAMETER STYLE JAVA
MODIFIES SQL DATA
EXTERNAL NAME 'emcshop.db.MigrationSprocs.migrate4_5';

CALL MIGRATE();
DROP PROCEDURE MIGRATE;

CREATE PROCEDURE UPDATE_ITEMS()
LANGUAGE JAVA PARAMETER STYLE JAVA
MODIFIES SQL DATA
EXTERNAL NAME 'emcshop.db.MigrationSprocs.updateItemsTable';

--don't drop
CALL UPDATE_ITEMS();